// <auto-generated />
using GoogleDrive;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoogleDrive.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210407143055_GoogleDrive.Models.ApplicationContextSeed")]
    partial class GoogleDriveModelsApplicationContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoogleDrive.Models.TrainingFiles", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileID");

                    b.ToTable("TrainingFile");

                    b.HasData(
                        new
                        {
                            FileID = 1,
                            FileName = "Temp1",
                            FilePath = "Test1"
                        },
                        new
                        {
                            FileID = 2,
                            FileName = "Temp2",
                            FilePath = "Test2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
